### ISSUE TITLE
Tasks to complete before publishing CP

### ISSUE THREAD

**Issue by masterDev1985** [dhyey20/cp-web#1]
- Remove loopback connector
- Clean up unneeded dependencies
- Fix the blockheight monitor
- Update documentation where necessary
- Answer git issues
- Pull in Braden paper maturity code
- Push to the official cp-web repository
- Mark all existing CP-web repos as deprecated
- Have other people test it
- Investigate using cloudant for the key value storage
- Store passwords so that we can verify logins later

**Comment by dhyey20** [comment]
@masterDev1985 everything except maturity code and storing passwords is good to go
